require: rubocop-rails

# 日本語のコメントを許容する
Style/AsciiComments:
  Enabled: false

# コメントは強要しない
Style/Documentation:
  Enabled: false

# `Api::GifscomController` みたいな形を強要する
Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
