version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: web.Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    environment:
      POSTGRES_HOST: postgres

  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: password
